import openpyxl
from openpyxl.styles import Font, PatternFill, Alignment, Border, Side
from openpyxl.utils import get_column_letter
from openpyxl.comments import Comment

wb = openpyxl.Workbook()
ws = wb.active
ws.title = "DCF Valuation"

# Grid lines visible
ws.views.sheetView[0].showGridLines = True

# Colors
NAVY = "1F4E79"       # Primary Headers
MED_BLUE = "2F5597"   # Secondary Headers
SOFT_BLUE = "D9E1F2"  # Section Subheaders
ACCENT_BLUE = "BDD7EE"# Base Case highlight / Active Case
ZEBRA_FILL = "F2F5F9" # Alternating row fill
WHITE = "FFFFFF"
GRAY_TEXT = "595959"

# Font definitions
font_title = Font(name="Calibri", size=16, bold=True, color="1F4E79")
font_subtitle = Font(name="Calibri", size=11, italic=True, color=GRAY_TEXT)
font_sec_hdr = Font(name="Calibri", size=11, bold=True, color=WHITE)
font_tbl_hdr = Font(name="Calibri", size=10, bold=True, color="000000")
font_subhdr = Font(name="Calibri", size=10, bold=True, color="1F4E79")
font_bold = Font(name="Calibri", size=10, bold=True, color="000000")
font_regular = Font(name="Calibri", size=10, bold=False, color="000000")
font_italic = Font(name="Calibri", size=9, italic=True, color=GRAY_TEXT)

# Fills
fill_navy = PatternFill(start_color=NAVY, end_color=NAVY, fill_type="solid")
fill_med_blue = PatternFill(start_color=MED_BLUE, end_color=MED_BLUE, fill_type="solid")
fill_soft_blue = PatternFill(start_color=SOFT_BLUE, end_color=SOFT_BLUE, fill_type="solid")
fill_accent_blue = PatternFill(start_color=ACCENT_BLUE, end_color=ACCENT_BLUE, fill_type="solid")
fill_zebra = PatternFill(start_color=ZEBRA_FILL, end_color=ZEBRA_FILL, fill_type="solid")

# Borders
thin_line = Side(border_style="thin", color="D9D9D9")
thick_bottom = Side(border_style="medium", color="1F4E79")
double_bottom = Side(border_style="double", color="1F4E79")
top_thin = Side(border_style="thin", color="1F4E79")

border_cell = Border(left=thin_line, right=thin_line, top=thin_line, bottom=thin_line)
border_header = Border(left=thin_line, right=thin_line, top=thin_line, bottom=thick_bottom)
border_total = Border(top=top_thin, bottom=double_bottom, left=thin_line, right=thin_line)

# Alignments
align_left = Alignment(horizontal="left", vertical="center")
align_right = Alignment(horizontal="right", vertical="center")
align_center = Alignment(horizontal="center", vertical="center")

# --- Title Block ---
ws["A1"] = "Spruce Power Holding Corporation (NYSE: SPRU)"
ws["A1"].font = font_title
ws["A2"] = "Institutional DCF Valuation Model | Report Date: August 17, 2026 | Generated by: Gemini 3.7 Flash | SEC 10-Q (Q2 2026)"
ws["A2"].font = font_subtitle

# --- Scenario Selector ---
ws["A4"] = "Active Scenario Selector:"
ws["A4"].font = font_bold
ws["B4"] = 2
ws["B4"].font = Font(name="Calibri", size=11, bold=True, color="FFFFFF")
ws["B4"].fill = fill_navy
ws["B4"].alignment = align_center
ws["B4"].comment = Comment("Case Selector: 1 = Bear Case, 2 = Base Case, 3 = Bull Case", "Model Builder")

ws["C4"] = '=IF(B4=1,"[1] BEAR CASE",IF(B4=2,"[2] BASE CASE (Active)","[3] BULL CASE"))'
ws["C4"].font = Font(name="Calibri", size=11, bold=True, color="1F4E79")
ws["C4"].alignment = align_left

# Function to style a merged section header
def add_section_header(row, title, max_col="G"):
    ws[f"A{row}"] = title
    ws[f"A{row}"].font = font_sec_hdr
    ws[f"A{row}"].fill = fill_navy
    ws[f"A{row}"].alignment = align_left
    ws.merge_cells(f"A{row}:{max_col}{row}")
    for col_idx in range(1, 8):
        c = ws.cell(row=row, column=col_idx)
        c.fill = fill_navy

# --- Section I: Market Data & Balance Sheet ---
add_section_header(6, "I. MARKET DATA & BALANCE SHEET INPUTS (as of Q2 2026 Form 10-Q)")

market_inputs = [
    ("Current Stock Price ($)", 1.81, "$#,##0.00", "Market close price as of August 2026", "B7"),
    ("Diluted Shares Outstanding (M)", 21.120, "#,##0.00", "SEC Form 10-Q filed August 13, 2026 (Common shares 21.12M)", "B8"),
    ("Implied Market Capitalization ($M)", "=B7*B8", "$#,##0.00", None, "B9"),
    ("Cash and Cash Equivalents ($M)", 44.660, "$#,##0.00", "SEC Form 10-Q June 30, 2026 (Unrestricted cash)", "B10"),
    ("Restricted Cash ($M)", 36.883, "$#,##0.00", "SEC Form 10-Q June 30, 2026 (Project debt debt-service reserve)", "B11"),
    ("Total Cash & Restricted Cash ($M)", "=B10+B11", "$#,##0.00", None, "B12"),
    ("Current Non-Recourse Debt ($M)", 269.617, "$#,##0.00", "SEC Form 10-Q June 30, 2026 (Current portion of non-recourse debt)", "B13"),
    ("Non-Current Non-Recourse Debt ($M)", 392.958, "$#,##0.00", "SEC Form 10-Q June 30, 2026 (Long-term non-recourse debt)", "B14"),
    ("Total Non-Recourse Debt ($M)", "=B13+B14", "$#,##0.00", None, "B15"),
    ("Net Debt ($M)", "=B15-B12", "$#,##0.00", None, "B16"),
    ("Effective Tax Rate (%)", 0.210, "0.0%", "US Federal statutory corporate income tax rate", "B17"),
]

for idx, (label, val, num_fmt, comment_text, cell_ref) in enumerate(market_inputs, start=7):
    ws[f"A{idx}"] = label
    ws[f"A{idx}"].font = font_bold if "=" in str(val) else font_regular
    ws[f"A{idx}"].border = border_cell
    
    ws[f"B{idx}"] = val
    ws[f"B{idx}"].font = font_bold if "=" in str(val) else font_regular
    ws[f"B{idx}"].number_format = num_fmt
    ws[f"B{idx}"].alignment = align_right
    ws[f"B{idx}"].border = border_cell
    if comment_text:
        ws[f"B{idx}"].comment = Comment(comment_text, "SEC 10-Q")

# --- Section II: Scenario Assumptions ---
add_section_header(19, "II. SCENARIO ASSUMPTIONS & DRIVER BLOCKS")

# Column headers
headers_s2 = ["Driver / Assumption", "FY2026E", "FY2027E", "FY2028E", "FY2029E", "FY2030E", "Terminal / WACC"]
for col_idx, text in enumerate(headers_s2, start=1):
    c = ws.cell(row=20, column=col_idx, value=text)
    c.font = font_tbl_hdr
    c.fill = fill_soft_blue
    c.alignment = align_center if col_idx > 1 else align_left
    c.border = border_header

# Scenario Data
scenario_blocks = [
    # (Title, start_row, [ (label, [y1..y5], terminal_val, fmt) ])
    ("Bear Case Assumptions (Selector = 1)", 21, [
        ("  Revenue Growth (%)", [0.020, 0.020, 0.015, 0.015, 0.010], 0.015, "0.0%"),
        ("  EBIT Margin (%)", [0.200, 0.195, 0.190, 0.185, 0.180], 0.105, "0.0%"),
        ("  D&A (% of Revenue)", [0.280, 0.280, 0.280, 0.280, 0.280], None, "0.0%"),
        ("  CapEx (% of Revenue)", [0.035, 0.035, 0.035, 0.035, 0.035], None, "0.0%"),
        ("  Δ NWC (% of Δ Revenue)", [0.015, 0.015, 0.015, 0.015, 0.015], None, "0.0%"),
    ]),
    ("Base Case Assumptions (Selector = 2)", 27, [
        ("  Revenue Growth (%)", [0.050, 0.045, 0.040, 0.035, 0.030], 0.025, "0.0%"),
        ("  EBIT Margin (%)", [0.225, 0.230, 0.235, 0.240, 0.250], 0.095, "0.0%"),
        ("  D&A (% of Revenue)", [0.280, 0.280, 0.280, 0.280, 0.280], None, "0.0%"),
        ("  CapEx (% of Revenue)", [0.032, 0.032, 0.032, 0.032, 0.032], None, "0.0%"),
        ("  Δ NWC (% of Δ Revenue)", [0.015, 0.015, 0.015, 0.015, 0.015], None, "0.0%"),
    ]),
    ("Bull Case Assumptions (Selector = 3)", 33, [
        ("  Revenue Growth (%)", [0.080, 0.070, 0.060, 0.050, 0.040], 0.030, "0.0%"),
        ("  EBIT Margin (%)", [0.240, 0.250, 0.260, 0.270, 0.280], 0.090, "0.0%"),
        ("  D&A (% of Revenue)", [0.280, 0.280, 0.280, 0.280, 0.280], None, "0.0%"),
        ("  CapEx (% of Revenue)", [0.030, 0.030, 0.030, 0.030, 0.030], None, "0.0%"),
        ("  Δ NWC (% of Δ Revenue)", [0.015, 0.015, 0.015, 0.015, 0.015], None, "0.0%"),
    ]),
]

for title, sub_hdr_row, rows in scenario_blocks:
    ws[f"A{sub_hdr_row}"] = title
    ws[f"A{sub_hdr_row}"].font = font_subhdr
    ws[f"A{sub_hdr_row}"].fill = fill_soft_blue
    ws.merge_cells(f"A{sub_hdr_row}:G{sub_hdr_row}")
    for c_idx in range(1, 8):
        ws.cell(row=sub_hdr_row, column=c_idx).fill = fill_soft_blue
        ws.cell(row=sub_hdr_row, column=c_idx).border = border_cell
        
    for r_offset, (label, vals, term_val, num_fmt) in enumerate(rows, start=1):
        curr_r = sub_hdr_row + r_offset
        ws[f"A{curr_r}"] = label
        ws[f"A{curr_r}"].font = font_regular
        ws[f"A{curr_r}"].border = border_cell
        for c_idx, val in enumerate(vals, start=2):
            cell = ws.cell(row=curr_r, column=c_idx, value=val)
            cell.font = font_regular
            cell.number_format = num_fmt
            cell.alignment = align_right
            cell.border = border_cell
        if term_val is not None:
            cell_term = ws.cell(row=curr_r, column=7, value=term_val)
            cell_term.font = font_regular
            cell_term.number_format = num_fmt
            cell_term.alignment = align_right
            cell_term.border = border_cell
        else:
            cell_term = ws.cell(row=curr_r, column=7, value="")
            cell_term.border = border_cell

# Consolidated Active Drivers (Dynamic via CHOOSE formulas)
ws["A39"] = "Active Scenario Consolidated Drivers (Dynamic)"
ws["A39"].font = font_bold
ws["A39"].fill = fill_accent_blue
ws.merge_cells("A39:G39")
for c_idx in range(1, 8):
    ws.cell(row=39, column=c_idx).fill = fill_accent_blue
    ws.cell(row=39, column=c_idx).border = border_cell

active_driver_rows = [
    ("  Selected Revenue Growth (%)", 22, 28, 34, "0.0%"),
    ("  Selected EBIT Margin (%)", 23, 29, 35, "0.0%"),
    ("  Selected D&A (% of Revenue)", 24, 30, 36, "0.0%"),
    ("  Selected CapEx (% of Revenue)", 25, 31, 37, "0.0%"),
    ("  Selected Δ NWC (% of Δ Rev)", 26, 32, 38, "0.0%"),
]

for idx, (label, r_bear, r_base, r_bull, num_fmt) in enumerate(active_driver_rows, start=40):
    ws[f"A{idx}"] = label
    ws[f"A{idx}"].font = font_bold
    ws[f"A{idx}"].border = border_cell
    for c_idx in range(2, 7):
        col_let = get_column_letter(c_idx)
        cell = ws.cell(row=idx, column=c_idx)
        cell.value = f"=CHOOSE($B$4, {col_let}{r_bear}, {col_let}{r_base}, {col_let}{r_bull})"
        cell.font = font_bold
        cell.number_format = num_fmt
        cell.alignment = align_right
        cell.border = border_cell
    
    # Terminal / WACC in column G
    if idx == 40: # Terminal g
        cell_g = ws.cell(row=idx, column=7, value=f"=CHOOSE($B$4, G22, G28, G34)")
        cell_g.font = font_bold
        cell_g.number_format = "0.0%"
        cell_g.alignment = align_right
        cell_g.border = border_cell
    elif idx == 41: # WACC
        cell_g = ws.cell(row=idx, column=7, value=f"=CHOOSE($B$4, G23, G29, G35)")
        cell_g.font = font_bold
        cell_g.number_format = "0.0%"
        cell_g.alignment = align_right
        cell_g.border = border_cell
    else:
        cell_g = ws.cell(row=idx, column=7, value="")
        cell_g.border = border_cell

# --- Section III: Free Cash Flow Projections ---
add_section_header(47, "III. UNLEVERED FREE CASH FLOW (UFCF) PROJECTIONS")

headers_s3 = ["Line Item ($M)", "LTM Base", "FY2026E", "FY2027E", "FY2028E", "FY2029E", "FY2030E"]
for col_idx, text in enumerate(headers_s3, start=1):
    c = ws.cell(row=48, column=col_idx, value=text)
    c.font = font_tbl_hdr
    c.fill = fill_soft_blue
    c.alignment = align_center if col_idx > 1 else align_left
    c.border = border_header

# Row 49: Revenue Growth Rate
ws["A49"] = "Revenue Growth Rate (%)"
ws["A49"].font = font_regular
ws["A49"].border = border_cell
ws["B49"] = "—"
ws["B49"].alignment = align_center
ws["B49"].border = border_cell
for c_idx in range(3, 8):
    col_let = get_column_letter(c_idx)
    # Map to col C..G in row 40 (Active revenue growth)
    driver_col = get_column_letter(c_idx - 1)
    cell = ws.cell(row=49, column=c_idx, value=f"={driver_col}40")
    cell.font = font_regular
    cell.number_format = "0.0%"
    cell.alignment = align_right
    cell.border = border_cell

# Row 50: Total Revenue
ws["A50"] = "Total Revenue ($M)"
ws["A50"].font = font_bold
ws["A50"].border = border_cell
ws["B50"] = 108.48
ws["B50"].font = font_bold
ws["B50"].number_format = "$#,##0.00"
ws["B50"].alignment = align_right
ws["B50"].border = border_cell
ws["B50"].comment = Comment("LTM Revenue as of June 30, 2026 Form 10-Q", "SEC 10-Q")

ws["C50"] = "=B50*(1+C49)"
ws["D50"] = "=C50*(1+D49)"
ws["E50"] = "=D50*(1+E49)"
ws["F50"] = "=E50*(1+F49)"
ws["G50"] = "=F50*(1+G49)"
for c_idx in range(3, 8):
    c = ws.cell(row=50, column=c_idx)
    c.font = font_bold
    c.number_format = "$#,##0.00"
    c.alignment = align_right
    c.border = border_cell

# Row 51: EBIT Margin (%)
ws["A51"] = "EBIT Margin (%)"
ws["A51"].font = font_regular
ws["A51"].border = border_cell
ws["B51"] = "=B52/B50"
ws["B51"].font = font_regular
ws["B51"].number_format = "0.0%"
ws["B51"].alignment = align_right
ws["B51"].border = border_cell
for c_idx in range(3, 8):
    driver_col = get_column_letter(c_idx - 1)
    cell = ws.cell(row=51, column=c_idx, value=f"={driver_col}41")
    cell.font = font_regular
    cell.number_format = "0.0%"
    cell.alignment = align_right
    cell.border = border_cell

# Row 52: Operating Income (EBIT)
ws["A52"] = "Operating Income (EBIT) ($M)"
ws["A52"].font = font_bold
ws["A52"].border = border_cell
ws["B52"] = 24.33
ws["B52"].font = font_bold
ws["B52"].number_format = "$#,##0.00"
ws["B52"].alignment = align_right
ws["B52"].border = border_cell
ws["B52"].comment = Comment("LTM EBIT as of June 30, 2026 Form 10-Q", "SEC 10-Q")

for c_idx in range(3, 8):
    col_let = get_column_letter(c_idx)
    cell = ws.cell(row=52, column=c_idx, value=f"={col_let}50*{col_let}51")
    cell.font = font_bold
    cell.number_format = "$#,##0.00"
    cell.alignment = align_right
    cell.border = border_cell

# Row 53: (-) Taxes
ws["A53"] = "(-) Provision for Taxes ($M)"
ws["A53"].font = font_regular
ws["A53"].border = border_cell
ws["B53"] = "—"
ws["B53"].alignment = align_center
ws["B53"].border = border_cell
for c_idx in range(3, 8):
    col_let = get_column_letter(c_idx)
    cell = ws.cell(row=53, column=c_idx, value=f"={col_let}52*$B$17")
    cell.font = font_regular
    cell.number_format = "($#,##0.00);($#,##0.00);$0.00"
    cell.alignment = align_right
    cell.border = border_cell

# Row 54: NOPAT
ws["A54"] = "Net Operating Profit After Tax (NOPAT) ($M)"
ws["A54"].font = font_bold
ws["A54"].border = border_cell
ws["B54"] = "—"
ws["B54"].alignment = align_center
ws["B54"].border = border_cell
for c_idx in range(3, 8):
    col_let = get_column_letter(c_idx)
    cell = ws.cell(row=54, column=c_idx, value=f"={col_let}52-{col_let}53")
    cell.font = font_bold
    cell.number_format = "$#,##0.00"
    cell.alignment = align_right
    cell.border = border_cell

# Row 55: (+) D&A
ws["A55"] = "(+) Depreciation & Amortization (D&A) ($M)"
ws["A55"].font = font_regular
ws["A55"].border = border_cell
ws["B55"] = 30.50
ws["B55"].font = font_regular
ws["B55"].number_format = "$#,##0.00"
ws["B55"].alignment = align_right
ws["B55"].border = border_cell
ws["B55"].comment = Comment("LTM D&A from Form 10-Q", "SEC 10-Q")
for c_idx in range(3, 8):
    col_let = get_column_letter(c_idx)
    driver_col = get_column_letter(c_idx - 1)
    cell = ws.cell(row=55, column=c_idx, value=f"={col_let}50*{driver_col}42")
    cell.font = font_regular
    cell.number_format = "$#,##0.00"
    cell.alignment = align_right
    cell.border = border_cell

# Row 56: (-) CapEx
ws["A56"] = "(-) Capital Expenditures (CapEx) ($M)"
ws["A56"].font = font_regular
ws["A56"].border = border_cell
ws["B56"] = 3.50
ws["B56"].font = font_regular
ws["B56"].number_format = "($#,##0.00);($#,##0.00);$0.00"
ws["B56"].alignment = align_right
ws["B56"].border = border_cell
for c_idx in range(3, 8):
    col_let = get_column_letter(c_idx)
    driver_col = get_column_letter(c_idx - 1)
    cell = ws.cell(row=56, column=c_idx, value=f"={col_let}50*{driver_col}43")
    cell.font = font_regular
    cell.number_format = "($#,##0.00);($#,##0.00);$0.00"
    cell.alignment = align_right
    cell.border = border_cell

# Row 57: (-) Change in NWC
ws["A57"] = "(-) Change in Net Working Capital (Δ NWC) ($M)"
ws["A57"].font = font_regular
ws["A57"].border = border_cell
ws["B57"] = "—"
ws["B57"].alignment = align_center
ws["B57"].border = border_cell
for c_idx in range(3, 8):
    col_let = get_column_letter(c_idx)
    prev_col = get_column_letter(c_idx - 1)
    driver_col = get_column_letter(c_idx - 1)
    cell = ws.cell(row=57, column=c_idx, value=f"=({col_let}50-{prev_col}50)*{driver_col}44")
    cell.font = font_regular
    cell.number_format = "($#,##0.00);($#,##0.00);$0.00"
    cell.alignment = align_right
    cell.border = border_cell

# Row 58: Unlevered Free Cash Flow (UFCF)
ws["A58"] = "Unlevered Free Cash Flow (UFCF) ($M)"
ws["A58"].font = Font(name="Calibri", size=10, bold=True, color="1F4E79")
ws["A58"].fill = fill_accent_blue
ws["A58"].border = border_total
ws["B58"] = "—"
ws["B58"].alignment = align_center
ws["B58"].fill = fill_accent_blue
ws["B58"].border = border_total
for c_idx in range(3, 8):
    col_let = get_column_letter(c_idx)
    cell = ws.cell(row=58, column=c_idx, value=f"={col_let}54+{col_let}55-{col_let}56-{col_let}57")
    cell.font = Font(name="Calibri", size=10, bold=True, color="1F4E79")
    cell.fill = fill_accent_blue
    cell.number_format = "$#,##0.00"
    cell.alignment = align_right
    cell.border = border_total

# --- Section IV: Discounting & Present Value ---
add_section_header(60, "IV. DISCOUNTING & PRESENT VALUE (MID-YEAR CONVENTION)")

headers_s4 = ["Discount Parameters", "", "Year 1 (FY26E)", "Year 2 (FY27E)", "Year 3 (FY28E)", "Year 4 (FY29E)", "Year 5 (FY30E)"]
for col_idx, text in enumerate(headers_s4, start=1):
    c = ws.cell(row=61, column=col_idx, value=text)
    c.font = font_tbl_hdr
    c.fill = fill_soft_blue
    c.alignment = align_center if col_idx > 2 else align_left
    c.border = border_header

# Row 62: Discount Period
ws["A62"] = "Discount Period (Years - Mid-Year)"
ws["A62"].font = font_regular
ws["A62"].border = border_cell
ws["B62"] = ""
ws["B62"].border = border_cell
periods = [0.5, 1.5, 2.5, 3.5, 4.5]
for c_idx, p in enumerate(periods, start=3):
    cell = ws.cell(row=62, column=c_idx, value=p)
    cell.font = font_regular
    cell.number_format = "0.0"
    cell.alignment = align_center
    cell.border = border_cell

# Row 63: Discount Factor
ws["A63"] = "Discount Factor [ 1 / (1 + WACC)^t ]"
ws["A63"].font = font_regular
ws["A63"].border = border_cell
ws["B63"] = ""
ws["B63"].border = border_cell
for c_idx in range(3, 8):
    col_let = get_column_letter(c_idx)
    cell = ws.cell(row=63, column=c_idx, value=f"=1/(1+$G$41)^{col_let}62")
    cell.font = font_regular
    cell.number_format = "0.0000"
    cell.alignment = align_right
    cell.border = border_cell

# Row 64: Present Value of UFCF
ws["A64"] = "Present Value of UFCF ($M)"
ws["A64"].font = font_bold
ws["A64"].border = border_cell
ws["B64"] = ""
ws["B64"].border = border_cell
for c_idx in range(3, 8):
    col_let = get_column_letter(c_idx)
    cell = ws.cell(row=64, column=c_idx, value=f"={col_let}58*{col_let}63")
    cell.font = font_bold
    cell.number_format = "$#,##0.00"
    cell.alignment = align_right
    cell.border = border_cell

# Row 65: Sum of PV of Explicit Cash Flows
ws["A65"] = "Cumulative PV of 5-Year Explicit Cash Flows ($M)"
ws["A65"].font = font_bold
ws["A65"].fill = fill_soft_blue
ws["A65"].border = border_total
ws["B65"] = "=SUM(C64:G64)"
ws["B65"].font = font_bold
ws["B65"].fill = fill_soft_blue
ws["B65"].number_format = "$#,##0.00"
ws["B65"].alignment = align_right
ws["B65"].border = border_total
ws.merge_cells("C65:G65")
for c_idx in range(3, 8):
    ws.cell(row=65, column=c_idx).fill = fill_soft_blue
    ws.cell(row=65, column=c_idx).border = border_total

# --- Section V: Terminal Value & Valuation Summary ---
add_section_header(67, "V. TERMINAL VALUE & VALUATION SUMMARY")

val_summary_items = [
    ("Terminal Value Assumptions & Calculation:", None, None, None, True),
    ("  Final Year Projected UFCF (FY2030E) ($M)", "=G58", "$#,##0.00", None, False),
    ("  Perpetual Terminal Growth Rate (g)", "=$G$40", "0.0%", None, False),
    ("  WACC (Discount Rate)", "=$G$41", "0.0%", None, False),
    ("  Terminal Year Cash Flow ($M)", "=B69*(1+B70)", "$#,##0.00", None, False),
    ("  Terminal Value at FY2030E ($M)", "=B72/(B71-B70)", "$#,##0.00", None, False),
    ("  PV of Terminal Value ($M)", "=B73/(1+B71)^4.5", "$#,##0.00", None, False),
    ("  Terminal Value as % of Enterprise Value", "=B74/B79", "0.0%", None, False),
    ("Enterprise Value to Equity Value Bridge ($M):", None, None, None, True),
    ("  PV of Explicit 5-Year Cash Flows ($M)", "=B65", "$#,##0.00", None, False),
    ("  (+) PV of Terminal Value ($M)", "=B74", "$#,##0.00", None, False),
    ("Enterprise Value (EV) ($M)", "=B77+B78", "$#,##0.00", None, False),
    ("  (-) Total Non-Recourse Debt ($M)", "=$B$15", "($#,##0.00);($#,##0.00);$0.00", None, False),
    ("  (+) Total Cash & Equivalents ($M)", "=$B$12", "$#,##0.00", None, False),
    ("  (-) Net Debt ($M)", "=$B$16", "($#,##0.00);($#,##0.00);$0.00", None, False),
    ("Implied Equity Value ($M)", "=B79-B82", "$#,##0.00", None, False),
    ("  Diluted Shares Outstanding (M)", "=$B$8", "#,##0.00", None, False),
    ("Implied Price per Share ($)", "=B83/B84", "$#,##0.00", None, False),
    ("Current Market Share Price ($)", "=$B$7", "$#,##0.00", None, False),
    ("Implied Upside / (Downside) (%)", "=(B85/B86)-1", "+0.0%;-0.0%;0.0%", None, False),
]

# Write Valuation Summary
current_r = 68
for item in val_summary_items:
    label, formula_val, num_fmt, comment_t, is_header = item
    if is_header:
        ws[f"A{current_r}"] = label
        ws[f"A{current_r}"].font = font_subhdr
        ws[f"A{current_r}"].fill = fill_soft_blue
        ws.merge_cells(f"A{current_r}:G{current_r}")
        for c_idx in range(1, 8):
            ws.cell(row=current_r, column=c_idx).fill = fill_soft_blue
            ws.cell(row=current_r, column=c_idx).border = border_cell
    else:
        ws[f"A{current_r}"] = label
        is_highlight = label in ["Enterprise Value (EV) ($M)", "Implied Equity Value ($M)", "Implied Price per Share ($)", "Implied Upside / (Downside) (%)"]
        ws[f"A{current_r}"].font = font_bold if is_highlight else font_regular
        ws[f"A{current_r}"].border = border_cell
        if is_highlight:
            ws[f"A{current_r}"].fill = fill_accent_blue
            
        ws[f"B{current_r}"] = formula_val
        ws[f"B{current_r}"].font = font_bold if is_highlight else font_regular
        ws[f"B{current_r}"].number_format = num_fmt
        ws[f"B{current_r}"].alignment = align_right
        ws[f"B{current_r}"].border = border_cell
        if is_highlight:
            ws[f"B{current_r}"].fill = fill_accent_blue
    current_r += 1

# --- Section VI: Sensitivity Analysis ---
add_section_header(89, "VI. SENSITIVITY ANALYSIS (5x5 INSTITUTIONAL VALUATION GRIDS)")

# Table 1: WACC vs Terminal Growth Rate
ws["A90"] = "Sensitivity Table 1: Implied Share Price ($) vs. WACC and Perpetual Terminal Growth Rate (g)"
ws["A90"].font = font_subhdr
ws.merge_cells("A90:G90")

ws["A91"] = "WACC \\ g"
ws["A91"].font = font_tbl_hdr
ws["A91"].fill = fill_soft_blue
ws["A91"].alignment = align_center
ws["A91"].border = border_header

t1_g_values = [0.015, 0.020, 0.025, 0.030, 0.035]
t1_wacc_values = [0.085, 0.090, 0.095, 0.100, 0.105]

for col_idx, g_val in enumerate(t1_g_values, start=2):
    c = ws.cell(row=91, column=col_idx, value=g_val)
    c.font = font_tbl_hdr
    c.fill = fill_accent_blue if col_idx == 4 else fill_soft_blue
    c.number_format = "0.0%"
    c.alignment = align_center
    c.border = border_header

for row_idx, w_val in enumerate(t1_wacc_values, start=92):
    ws.cell(row=row_idx, column=1, value=w_val)
    ws.cell(row=row_idx, column=1).font = font_tbl_hdr
    ws.cell(row=row_idx, column=1).fill = fill_accent_blue if row_idx == 94 else fill_soft_blue
    ws.cell(row=row_idx, column=1).number_format = "0.0%"
    ws.cell(row=row_idx, column=1).alignment = align_center
    ws.cell(row=row_idx, column=1).border = border_cell
    
    for col_idx in range(2, 7):
        col_let = get_column_letter(col_idx)
        # Full DCF recalculation formula:
        # PV FCFs: sum_{t=1..5} UFCF_t / (1 + WACC)^p_t
        # PV TV: (UFCF_5 * (1 + g) / (WACC - g)) / (1 + WACC)^4.5
        # Equity = EV - Net Debt = (PV_FCFs + PV_TV) - $B$16
        # Share Price = Equity / $B$8
        formula = (
            f"=(($C$58/(1+$A{row_idx})^0.5 + $D$58/(1+$A{row_idx})^1.5 + $E$58/(1+$A{row_idx})^2.5 + "
            f"$F$58/(1+$A{row_idx})^3.5 + $G$58/(1+$A{row_idx})^4.5 + "
            f"($G$58*(1+{col_let}$91)/($A{row_idx}-{col_let}$91))/(1+$A{row_idx})^4.5) - $B$16)/$B$8"
        )
        cell = ws.cell(row=row_idx, column=col_idx, value=formula)
        cell.font = font_bold if (row_idx == 94 and col_idx == 4) else font_regular
        cell.number_format = "$#,##0.00;($#,##0.00);$0.00"
        cell.alignment = align_right
        cell.border = border_cell
        if row_idx == 94 and col_idx == 4:
            cell.fill = fill_accent_blue  # Center cell = Base Case!

# Table 2: FY26-30 Revenue Growth Step vs Target EBIT Margin
ws["A98"] = "Sensitivity Table 2: Implied Share Price ($) vs. Revenue Growth Rate & Target FY30 EBIT Margin"
ws["A98"].font = font_subhdr
ws.merge_cells("A98:G98")

ws["A99"] = "EBIT Margin \\ Rev Growth"
ws["A99"].font = font_tbl_hdr
ws["A99"].fill = fill_soft_blue
ws["A99"].alignment = align_center
ws["A99"].border = border_header

t2_rev_growth = [0.030, 0.040, 0.050, 0.060, 0.070]
t2_ebit_margins = [0.210, 0.230, 0.250, 0.270, 0.290]

for col_idx, g_val in enumerate(t2_rev_growth, start=2):
    c = ws.cell(row=99, column=col_idx, value=g_val)
    c.font = font_tbl_hdr
    c.fill = fill_accent_blue if col_idx == 4 else fill_soft_blue
    c.number_format = "0.0%"
    c.alignment = align_center
    c.border = border_header

for row_idx, m_val in enumerate(t2_ebit_margins, start=100):
    ws.cell(row=row_idx, column=1, value=m_val)
    ws.cell(row=row_idx, column=1).font = font_tbl_hdr
    ws.cell(row=row_idx, column=1).fill = fill_accent_blue if row_idx == 102 else fill_soft_blue
    ws.cell(row=row_idx, column=1).number_format = "0.0%"
    ws.cell(row=row_idx, column=1).alignment = align_center
    ws.cell(row=row_idx, column=1).border = border_cell
    
    for col_idx in range(2, 7):
        col_let = get_column_letter(col_idx)
        # Scaled DCF approximation from base drivers
        # Growth scale factor: (1 + {col_let}$99)/(1 + 0.05)
        # Margin scale factor: ($A{row_idx}/0.25)
        # Recalculate UFCF_5 and PV of UFCF directly with formulas
        formula = (
            f"=((($C$58*(1+({col_let}$99-0.050))*($A{row_idx}/0.25))/(1+$G$41)^0.5 + "
            f"($D$58*(1+({col_let}$99-0.050))*($A{row_idx}/0.25))/(1+$G$41)^1.5 + "
            f"($E$58*(1+({col_let}$99-0.050))*($A{row_idx}/0.25))/(1+$G$41)^2.5 + "
            f"($F$58*(1+({col_let}$99-0.050))*($A{row_idx}/0.25))/(1+$G$41)^3.5 + "
            f"($G$58*(1+({col_let}$99-0.050))*($A{row_idx}/0.25))/(1+$G$41)^4.5 + "
            f"(($G$58*(1+({col_let}$99-0.050))*($A{row_idx}/0.25)*(1+$G$40)/($G$41-$G$40))/(1+$G$41)^4.5)) - $B$16)/$B$8"
        )
        cell = ws.cell(row=row_idx, column=col_idx, value=formula)
        cell.font = font_bold if (row_idx == 102 and col_idx == 4) else font_regular
        cell.number_format = "$#,##0.00;($#,##0.00);$0.00"
        cell.alignment = align_right
        cell.border = border_cell
        if row_idx == 102 and col_idx == 4:
            cell.fill = fill_accent_blue  # Center cell = Base Case!

# Table 3: Beta vs Risk-Free Rate
ws["A106"] = "Sensitivity Table 3: Implied Share Price ($) vs. Beta & 10-Year Treasury Yield (Risk-Free Rate)"
ws["A106"].font = font_subhdr
ws.merge_cells("A106:G106")

ws["A107"] = "Beta \\ Risk-Free Rate"
ws["A107"].font = font_tbl_hdr
ws["A107"].fill = fill_soft_blue
ws["A107"].alignment = align_center
ws["A107"].border = border_header

t3_rf_values = [0.0325, 0.0375, 0.0425, 0.0475, 0.0525]
t3_beta_values = [1.25, 1.45, 1.65, 1.85, 2.05]

for col_idx, rf_val in enumerate(t3_rf_values, start=2):
    c = ws.cell(row=107, column=col_idx, value=rf_val)
    c.font = font_tbl_hdr
    c.fill = fill_accent_blue if col_idx == 4 else fill_soft_blue
    c.number_format = "0.00%"
    c.alignment = align_center
    c.border = border_header

for row_idx, beta_val in enumerate(t3_beta_values, start=108):
    ws.cell(row=row_idx, column=1, value=beta_val)
    ws.cell(row=row_idx, column=1).font = font_tbl_hdr
    ws.cell(row=row_idx, column=1).fill = fill_accent_blue if row_idx == 110 else fill_soft_blue
    ws.cell(row=row_idx, column=1).number_format = "0.00"
    ws.cell(row=row_idx, column=1).alignment = align_center
    ws.cell(row=row_idx, column=1).border = border_cell
    
    for col_idx in range(2, 7):
        col_let = get_column_letter(col_idx)
        # Derived WACC = 0.5 * (Rf + Beta * 0.055) + 0.5 * (0.075 * (1 - 0.21))
        # = 0.5 * ({col_let}$107 + $A{row_idx} * 0.055) + 0.029625
        wacc_expr = f"(0.5*({col_let}$107 + $A{row_idx}*0.055) + 0.029625)"
        formula = (
            f"=(($C$58/(1+{wacc_expr})^0.5 + $D$58/(1+{wacc_expr})^1.5 + $E$58/(1+{wacc_expr})^2.5 + "
            f"$F$58/(1+{wacc_expr})^3.5 + $G$58/(1+{wacc_expr})^4.5 + "
            f"($G$58*(1+$G$40)/({wacc_expr}-$G$40))/(1+{wacc_expr})^4.5) - $B$16)/$B$8"
        )
        cell = ws.cell(row=row_idx, column=col_idx, value=formula)
        cell.font = font_bold if (row_idx == 110 and col_idx == 4) else font_regular
        cell.number_format = "$#,##0.00;($#,##0.00);$0.00"
        cell.alignment = align_right
        cell.border = border_cell
        if row_idx == 110 and col_idx == 4:
            cell.fill = fill_accent_blue  # Center cell = Base Case!

# --- Column Widths Auto-fit ---
col_widths = {
    "A": 44,
    "B": 18,
    "C": 18,
    "D": 18,
    "E": 18,
    "F": 18,
    "G": 20
}
for col_let, width in col_widths.items():
    ws.column_dimensions[col_let].width = width

wb.save("SPRU_DCF_Model_Gemini-3.7-Flash_20260817.xlsx")
print("Saved SPRU_DCF_Model_Gemini-3.7-Flash_20260817.xlsx successfully.")
